
# how to create numpy's array
import numpy as np
a1=np.array([2,13,45,64,2,46,76])
print(*a1)

Dimensions in Arrays and how to create and access


In [ ]:
import numpy as np
#0-d
arr1=np.array(45)
print(arr1)
print(type(arr1))
print(arr1.ndim)#ndim is use for checking dimension of arr
print(arr1.size)#.size tell the total no. of element present in array
print(arr1.shape)# you will better understand in example 3

#1-d
arr2=np.array([2,3,4])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

#2-d
arr3=np.array([[2,3,4],[4,5,6]])
print(arr3)
print(type(arr3))
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)#ouput is (2,3) where 2->tell us about no. of 1 d present in 2 d and 3-> tell that no. of element present in each on 1d.

# same for 3d......nd

"""how to create dimension"""
arr4=np.array([3,4,5,6,2],ndmin=5)#ndmin=5 means minimum 5 dimension create not less than 5
print(arr4)
print("number of dimensions:",arr4.ndim)
#output below:
# [[[[[3 4 5 6 2]]]]]
# number of dimensions: 5

45
<class 'numpy.ndarray'>
0
1
()
[2 3 4]
<class 'numpy.ndarray'>
1
3
(3,)
[[2 3 4]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
[[[[[3 4 5 6 2]]]]]
number of dimensions: 5


Indexing in numpy
        ->it baically followed the python rule i.e 0-indexing and       negative base indexing.

In [ ]:
import numpy as np

#1d indexing
arr2=np.array([2,3,4])
print(arr2)
print(arr2[0])
print(arr2[-1])

#2d indexing 
arr3=np.array([[2,3,4],[4,5,6]])
print(arr3)

# 1st ways
print(arr3[0,0])
#output below:
# 2

#tradisational ways 
print(arr3[0][0])
#output below:
# 2

#negative indexing
print(arr3[-1])
#output below:
# [4 5 6]

print(arr3[-1][-1])
#output below:
# 6

[2 3 4]
2
4
[[2 3 4]
 [4 5 6]]
2
2
[4 5 6]
6


In [ ]:
"""copy vs view  Numpy array
        ->Copy:- create a copy of array and it not affect the original array
                and also original array change will not affect the copy array
        ->view:- only view the array not change any thing in original array
                when original array change then view show that change
"""
#code
import numpy as np
arr=np.array([1,2,3,4,5,6])

#copy
copy_arr=arr.copy()
print("copy array is:",copy_arr)
arr[0]=45# this change in original array only not in copy array because copy 
        #array store the array in different addhress
print("original array is with change:",arr)
print("copy array is:",copy_arr)

#view
view_array = arr.view()
arr[0] = 42

print(arr)
print(view_array)

#Check if Array Owns its Data
"""This is check by "base attribute" which return the "None" if it has view 
    else return array.
"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

copy array is: [1 2 3 4 5 6]
original array is with change: [45  2  3  4  5  6]
copy array is: [1 2 3 4 5 6]
[42  2  3  4  5  6]
[42  2  3  4  5  6]
None
[1 2 3 4 5]
