In [ ]:
            #|\ | |   |  |\  /| |___| \/
            #| \| |___|  | \/ | |     /  



# how to create numpy's array
import numpy as np
a1=np.array([2,13,45,64,2,46,76])
print(*a1)

Dimensions in Arrays and how to create and access


In [6]:
import numpy as np
#0-d
arr1=np.array(45)
print(arr1)
print(type(arr1))
print(arr1.ndim)#ndim is use for checking dimension of arr
print(arr1.size)#.size tell the total no. of element present in array
print(arr1.shape)# you will better understand in example 3

#1-d
arr2=np.array([2,3,4])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)

#2-d
arr3=np.array([[2,3,4],[4,5,6]])
print(arr3)
print(type(arr3))
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)#ouput is (2,3) where 2->tell us about no. of 1 d present in 2 d and 3-> tell that no. of element present in each on 1d.

# same for 3d......nd
"""how to create dimension"""
arr4=np.array([3,4,5,6,2],ndmin=5)#ndmin=5 means minimum 5 dimension create not less than 5
print(arr4)
print("number of dimensions:",arr4.ndim)
#output below:
# [[[[[3 4 5 6 2]]]]]
# number of dimensions: 5

#reshaping the array means change in dimension
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print("reshaping array is:",newarr)

#Unknown Dimension
    #->Pass -1 as the value, and NumPy will calculate this number for you.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)



45
<class 'numpy.ndarray'>
0
1
()
[2 3 4]
<class 'numpy.ndarray'>
1
3
(3,)
[[2 3 4]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
[[[[[3 4 5 6 2]]]]]
number of dimensions: 5
reshaping array is: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Indexing in numpy
        ->it baically followed the python rule i.e 0-indexing and       negative base indexing.

In [ ]:
import numpy as np

#1d indexing
arr2=np.array([2,3,4])
print(arr2)
print(arr2[0])
print(arr2[-1])

#2d indexing 
arr3=np.array([[2,3,4],[4,5,6]])
print(arr3)

# 1st ways
print(arr3[0,0])
#output below:
# 2

#tradisational ways 
print(arr3[0][0])
#output below:
# 2

#negative indexing
print(arr3[-1])
#output below:
# [4 5 6]

print(arr3[-1][-1])
#output below:
# 6

[2 3 4]
2
4
[[2 3 4]
 [4 5 6]]
2
2
[4 5 6]
6


In [ ]:
"""copy vs view  Numpy array
        ->Copy:- create a copy of array and it not affect the original array
                and also original array change will not affect the copy array
        ->view:- only view the array not change any thing in original array
                when original array change then view show that change
"""
#code
import numpy as np
arr=np.array([1,2,3,4,5,6])

#copy
copy_arr=arr.copy()
print("copy array is:",copy_arr)
arr[0]=45# this change in original array only not in copy array because copy 
        #array store the array in different addhress
print("original array is with change:",arr)
print("copy array is:",copy_arr)

#view
view_array = arr.view()
arr[0] = 42

print(arr)
print(view_array)

#Check if Array Owns its Data
"""This is check by "base attribute" which return the "None" if it has view 
    else return array.
"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

copy array is: [1 2 3 4 5 6]
original array is with change: [45  2  3  4  5  6]
copy array is: [1 2 3 4 5 6]
[42  2  3  4  5  6]
[42  2  3  4  5  6]
None
[1 2 3 4 5]


In [12]:
#Numpy array itration

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

#using nditer() methods
for x in np.nditer(arr):
  print(x,end=" ")
print()
  
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

1 2 3 4 5 6 7 8 
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
#numpy array joining

import numpy as np

#concatenate() function
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.concatenate((a1,a2))
print(a3)

#join 2d array along rows(axis=1)
"""axis tells NumPy the direction in which to perform the operation.
   Without axis, NumPy wouldn’t know how to combine, sum, or compare data.
   axis=0 means array have only 1 dimenson 
   axis=1 means array have only 2 dimenson 
   axis=2 means array have only 3 dimenson 
"""
a4=np.array([[1,2],[3,4]])
a5=np.array([[5,6],[7,8]])
arr=np.concatenate((a4,a5),axis=1)
print("2d array is with axis 1\n",arr)

#axis=2
a6=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a7=np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
arr=np.concatenate((a6,a7),axis=2)
print("3d array is with axis 2\n",arr)

#Joining Arrays Using Stack Functions
a8=np.array([1,2,3])
a9=np.array([1,2,3])
sarr=np.stack((a8,a9),axis=1)
print('sarr:-',sarr)

row_arr=np.hstack((a8,a9))
print("row_arr:-\n",row_arr)

col_arr = np.vstack((a8, a9))
print('col_arr\n',col_arr)

dept_arr = np.dstack((a8, a9))
print('dept_arr\n',dept_arr)
#note:- dept and sarr are give same out put


[1 2 3 4 5 6]
2d array is with axis 1
 [[1 2 5 6]
 [3 4 7 8]]
3d array is with axis 2
 [[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]
sarr:- [[1 1]
 [2 2]
 [3 3]]
row_arr:-
 [1 2 3 1 2 3]
col_arr
 [[1 2 3]
 [1 2 3]]
dept_arr
 [[[1 1]
  [2 2]
  [3 3]]]


In [14]:
#numpy Splitting array:-
'''
           """1.Splitting is reverse operation of Joining
              2."array_split()" is main to split array
              3.Similar alternates to vstack() and dstack() 
                are available as vsplit() and dsplit().
              4. The return value is a list containing arrays.
            """
            """we also have split() fun but if array's elements are not divided
               into sub array than it give error istead of array_split() split
            """
'''

import numpy as np

#1d
arr = np.array([1, 2, 3, 4, 5, 6])
# newarr = np.split(arr, 4)
# print("only split:\n",newarr) this line give error
newarr = np.array_split(arr, 3)
print("only array_split:\n",newarr)

#2d
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print("2d array is:\n",newarr)
newarr = np.array_split(arr, 3, axis=1)
print("2d array is with axis 1:\n",newarr)

only array_split:
 [array([1, 2]), array([3, 4]), array([5, 6])]
2d array is:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
2d array is with axis 1:
 [array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


In [23]:
#Numpy Searching Arrays
'''
    ->we use 'where()' function for searching
    ->it will return index where the element present in tuple
'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

'''
-> method called 'searchsorted()' which perform binary search in array 
  which find right place where the elenemt enter
'''
ar=np.array([3,4,5,2,8])
arr=np.searchsorted(ar,9)
print(arr)

#search multiple element
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

#Search From the Side
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

(array([3, 5, 6]),)
5
[1 2 3]
2


In [6]:
#Sort and Filter in numpy array
import numpy as np

#sort()
arr = np.array([3, 2, 0, 1])
sorted_array=np.sort(arr)
print('sorted_array is\n',sorted_array)

#sorting in 2d
arr = np.array([[3, 2, 4], [5, 0, 1]])
sorted_2d_arr=np.sort(arr)
print('sorted_2d_arr is\n',sorted_2d_arr)

'''
Note: This method returns a copy of the array,leaving the original
       array unchanged.
'''

#Filter
'''

'''
#example 1:
arr=np.array([41,42,45,35,78])
x=[True,False,True,False,True]
newarr=arr[x]
print("new array is:",newarr)

#example 2:
arr=np.array([54,76,89,33,21,59,65])
empty_arr=[]
for i in arr:
       if i>55:
              empty_arr.append(True)
       else:
              empty_arr.append(False)
print("empty_arr is ",empty_arr)
newarr=arr[empty_arr]
print("newarr is ",newarr)

#example 3:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

sorted_array is
 [0 1 2 3]
sorted_2d_arr is
 [[2 3 4]
 [0 1 5]]
new array is: [41 45 78]
empty_arr is  [False, True, True, False, False, True, True]
newarr is  [76 89 59 65]
[False False  True  True]
[43 44]


In [29]:
#revision and praticing of basic function
import numpy as np
arr=np.array([])
for i in range(0,5):
    arr=np.append(arr,i)
print(arr)

arr=np.array([],dtype='int')
for i in range(0,5):
    arr=np.append(arr,i)
print(arr)


[0. 1. 2. 3. 4.]
[0 1 2 3 4]


In [24]:
#---------------------Random Numbers in NumPy------------------------
import numpy as np
from numpy import random
x=random.randint(100)#for integer genration
y=random.rand()#for float
print(x)
print(y)

#for random array
x=random.randint(100,size=5)
print(x)

#2d array
x=random.randint(100,size=(3,5))
print(x)

#generate random number from given array's element by predefine function
#choice()
x = random.choice([3, 5, 7, 9])#also add size for making dimension array
print(x)

#example
x=random.randint(100, size=(2))
print(x)

25
0.5892452192585202
[41 61 19 89 18]
[[44 23 17 86 30]
 [44  4 89 43 14]
 [97 38 57 93 40]]
3
[22 68]
